package soap

import (
	"encoding/base64"
	"strings"
)

// attrXSIType maps an AD lDAPDisplayName (lowercase) to the xsi:type that
// ADWS expects for that attribute's values in <ad:value xsi:type="..."> elements.
// Only attributes requiring xsd:base64Binary are listed; all other syntaxes
// (Boolean, Integer, LargeInteger, all string variants, DN types, time types)
// serialize as xsd:string per the MS-ADDM §2.3.4 syntax-mapping table.
//
// The attribute→syntax mapping comes from the lDAPDisplayName / attributeSyntax
// pairs in the Microsoft Open Specifications schema LDF files (AD DS + AD LDS,
// Windows Server 2008 R2 through v1903, newest file wins on conflicts).
//
// The syntax→xsd:type mapping is authoritative from two specs:
//
//	[MS-ADTS] §3.1.1.2.2.2 "LDAP Representations" — defines the attributeSyntax
//	OID for each LDAP syntax (e.g. 2.5.5.17 → String(Sid)).
//
//	[MS-ADDM] §2.3.4 "Syntax Mapping" — defines the XML syntax (XMLSYN) used in
//	<ad:value xsi:type="XMLSYN"> for each LDAP syntax. Per that table, only three
//	LDAP syntaxes map to xsd:base64Binary:
//	  Object(Replica-Link)  (attributeSyntax 2.5.5.10 / oMSyntax 127) → xsd:base64Binary
//	  String(NT-Sec-Desc)   (attributeSyntax 2.5.5.15)                → xsd:base64Binary
//	  String(Octet)         (attributeSyntax 2.5.5.10 / oMSyntax 4)   → xsd:base64Binary
//	  String(Sid)           (attributeSyntax 2.5.5.17)                → xsd:base64Binary
//	All other syntaxes (Boolean 2.5.5.8, Integer 2.5.5.9, LargeInteger 2.5.5.16,
//	all DN/string/time variants) map to xsd:string and are omitted from this map.
var attrXSIType = map[string]string{
	"acstimeofdayschedulex":                              "xsd:base64Binary",
	"acstimeofdayschedulez":                              "xsd:base64Binary",
	"additionalinformation":                              "xsd:base64Binary",
	"allowedchildclasseseffective":                       "xsd:base64Binary",
	"attributeid":                                        "xsd:base64Binary",
	"attributesecurityguid":                              "xsd:base64Binary",
	"attributesyntax":                                    "xsd:base64Binary",
	"auxiliaryclass":                                     "xsd:base64Binary",
	"cacertificate":                                      "xsd:base64Binary",
	"catalogs":                                           "xsd:base64Binary",
	"categories":                                         "xsd:base64Binary",
	"certificate":                                        "xsd:base64Binary",
	"certificaterevocationlist":                          "xsd:base64Binary",
	"certificatetemplates":                               "xsd:base64Binary",
	"connectionlist":                                     "xsd:base64Binary",
	"controlaccessrights":                                "xsd:base64Binary",
	"crosscertificatepair":                               "xsd:base64Binary",
	"currentvalue":                                       "xsd:base64Binary",
	"dbcspwd":                                            "xsd:base64Binary",
	"defaultclassstoreguid":                              "xsd:base64Binary",
	"defaultobjectcategory":                              "xsd:base64Binary",
	"defaultsecuritydescriptor":                          "xsd:base64Binary",
	"deltacrl":                                           "xsd:base64Binary",
	"deltatcrl":                                          "xsd:base64Binary",
	"dfsroot":                                            "xsd:base64Binary",
	"dnsproperty":                                        "xsd:base64Binary",
	"dnsrecord":                                          "xsd:base64Binary",
	"dscoremutex":                                        "xsd:base64Binary",
	"dspclusterid":                                       "xsd:base64Binary",
	"effectiverevocationobject":                          "xsd:base64Binary",
	"extendedattributeinfo":                              "xsd:base64Binary",
	"extendedclassinfo":                                  "xsd:base64Binary",
	"extracolumns":                                       "xsd:base64Binary",
	"frsreplica2guid":                                    "xsd:base64Binary",
	"frsreplicasetguid":                                  "xsd:base64Binary",
	"frsrootsecurity":                                    "xsd:base64Binary",
	"frsversion":                                         "xsd:base64Binary",
	"frsversionguid":                                     "xsd:base64Binary",
	"generatedrules":                                     "xsd:base64Binary",
	"groupmembershipsaw":                                 "xsd:base64Binary",
	"haspartialreplicans":                                "xsd:base64Binary",
	"implementedcategories":                              "xsd:base64Binary",
	"initialauthincoming":                                "xsd:base64Binary",
	"initialauthoutgoing":                                "xsd:base64Binary",
	"invocationid":                                       "xsd:base64Binary",
	"ipsecdata":                                          "xsd:base64Binary",
	"ipsecid":                                            "xsd:base64Binary",
	"ipsecownersreference":                               "xsd:base64Binary",
	"ipsecprimaryname":                                   "xsd:base64Binary",
	"ipsecprimaryreference":                              "xsd:base64Binary",
	"ipsecreference":                                     "xsd:base64Binary",
	"jpegphoto":                                          "xsd:base64Binary",
	"keywords":                                           "xsd:base64Binary",
	"lastknowngoodvalue":                                 "xsd:base64Binary",
	"ldapipdeniallist":                                   "xsd:base64Binary",
	"linkcredentials":                                    "xsd:base64Binary",
	"lmowfpassword":                                      "xsd:base64Binary",
	"loginworkstations":                                  "xsd:base64Binary",
	"logonhours":                                         "xsd:base64Binary",
	"logonworkstation":                                   "xsd:base64Binary",
	"managedpasswordid":                                  "xsd:base64Binary",
	"managedpasswordpreviousid":                          "xsd:base64Binary",
	"masterguid":                                         "xsd:base64Binary",
	"mastersoname":                                       "xsd:base64Binary",
	"meetingblob":                                        "xsd:base64Binary",
	"memberof":                                           "xsd:base64Binary",
	"moniker":                                            "xsd:base64Binary",
	"monikerclsid":                                       "xsd:base64Binary",
	"ms-dn-advsearch":                                    "xsd:base64Binary",
	"ms-ds-additionalsamaccountname":                     "xsd:base64Binary",
	"ms-ds-additionalupnsuffix":                          "xsd:base64Binary",
	"ms-ds-allowedtoactonbehalfofotheridentity":          "xsd:base64Binary",
	"ms-ds-ancestoridsvector":                            "xsd:base64Binary",
	"ms-ds-azscopename":                                  "xsd:base64Binary",
	"ms-ds-azscopes":                                     "xsd:base64Binary",
	"ms-ds-aztasks":                                      "xsd:base64Binary",
	"ms-ds-aztasksforcedrole":                            "xsd:base64Binary",
	"ms-ds-aztasksthatapplytooperation":                  "xsd:base64Binary",
	"ms-ds-birtdatesid":                                  "xsd:base64Binary",
	"ms-ds-cacerts":                                      "xsd:base64Binary",
	"ms-ds-claimattributesource":                         "xsd:base64Binary",
	"ms-ds-claimshareswithresourcetype":                  "xsd:base64Binary",
	"ms-ds-claimtypelist":                                "xsd:base64Binary",
	"ms-ds-claimvaluesonlyforrsc":                        "xsd:base64Binary",
	"ms-ds-consistencychild":                             "xsd:base64Binary",
	"ms-ds-consistencyguid":                              "xsd:base64Binary",
	"ms-ds-credentialpolicysilo":                         "xsd:base64Binary",
	"ms-ds-enabledfeature":                               "xsd:base64Binary",
	"ms-ds-enabledfeaturebl":                             "xsd:base64Binary",
	"ms-ds-filtereditems":                                "xsd:base64Binary",
	"ms-ds-gmsaid":                                       "xsd:base64Binary",
	"ms-ds-groupmanagedserviceaccount":                   "xsd:base64Binary",
	"ms-ds-has-instantiated-ncs":                         "xsd:base64Binary",
	"ms-ds-isdmsamasterforcomputer":                      "xsd:base64Binary",
	"ms-ds-isdmsamasterforcomputerbl":                    "xsd:base64Binary",
	"ms-ds-isdomainforgmsa":                              "xsd:base64Binary",
	"ms-ds-isdomainforgmsabl":                            "xsd:base64Binary",
	"ms-ds-ismanagedbyadsforgmsa":                        "xsd:base64Binary",
	"ms-ds-keycredentiallink":                            "xsd:base64Binary",
	"ms-ds-keycredentiallinkbl":                          "xsd:base64Binary",
	"ms-ds-krbtgtlink":                                   "xsd:base64Binary",
	"ms-ds-krbtgtlinkbl":                                 "xsd:base64Binary",
	"ms-ds-lastknownrdn":                                 "xsd:base64Binary",
	"ms-ds-localeffectivecredentialpolicies":             "xsd:base64Binary",
	"ms-ds-managedpassword":                              "xsd:base64Binary",
	"ms-ds-managedpasswordid":                            "xsd:base64Binary",
	"ms-ds-managedpasswordpreviousid":                    "xsd:base64Binary",
	"ms-ds-memberoftrainstivereplicationgroup":            "xsd:base64Binary",
	"ms-ds-memberoftransitivereplicationgroup":            "xsd:base64Binary",
	"ms-ds-memberstransitive":                            "xsd:base64Binary",
	"ms-ds-memberstransitiveforgrouplink":                "xsd:base64Binary",
	"ms-ds-membertrainsitivereplicationgroup":             "xsd:base64Binary",
	"ms-ds-membertrainstivereplicationgroup":              "xsd:base64Binary",
	"ms-ds-nc-repl-cursors":                              "xsd:base64Binary",
	"ms-ds-nc-repl-inbound-neighbors":                    "xsd:base64Binary",
	"ms-ds-nc-repl-outbound-neighbors":                   "xsd:base64Binary",
	"ms-ds-ncincomingcursors":                            "xsd:base64Binary",
	"ms-ds-ncincomingcursorsraw":                         "xsd:base64Binary",
	"ms-ds-nckeyvaluestore":                              "xsd:base64Binary",
	"ms-ds-ncoutgoingcursors":                            "xsd:base64Binary",
	"ms-ds-ncoutgoingcursorsraw":                         "xsd:base64Binary",
	"ms-ds-ncsupportedextendedoperations":                "xsd:base64Binary",
	"ms-ds-objectreferencenctype":                        "xsd:base64Binary",
	"ms-ds-operationsforauthrpolicy":                     "xsd:base64Binary",
	"ms-ds-optimizedfilter":                              "xsd:base64Binary",
	"ms-ds-optionalfeatureguid":                          "xsd:base64Binary",
	"ms-ds-parentdistname":                               "xsd:base64Binary",
	"ms-ds-primarycomputerbl":                            "xsd:base64Binary",
	"ms-ds-pso-applies-to":                               "xsd:base64Binary",
	"ms-ds-pso-appliestobl":                              "xsd:base64Binary",
	"ms-ds-replattributetobesynced":                      "xsd:base64Binary",
	"ms-ds-resolvesam":                                   "xsd:base64Binary",
	"ms-ds-retiredreplncsiagnatures":                     "xsd:base64Binary",
	"ms-ds-revealeddsas":                                 "xsd:base64Binary",
	"ms-ds-revealedlist":                                 "xsd:base64Binary",
	"ms-ds-revealedlistbl":                               "xsd:base64Binary",
	"ms-ds-revealeduser":                                 "xsd:base64Binary",
	"ms-ds-revealedusers":                                "xsd:base64Binary",
	"ms-ds-revelant-authz-policy":                        "xsd:base64Binary",
	"ms-ds-rocapasswordreplicationpolicy":                "xsd:base64Binary",
	"ms-ds-rocapasswordreplicationpolicynegative":        "xsd:base64Binary",
	"ms-ds-site-affinity":                                "xsd:base64Binary",
	"ms-ds-source-object-dn":                             "xsd:base64Binary",
	"ms-ds-sra-authpolicies":                             "xsd:base64Binary",
	"ms-ds-transitivememberof":                           "xsd:base64Binary",
	"ms-ds-updatescript":                                 "xsd:base64Binary",
	"ms-ds-userauthpolicysilobl":                         "xsd:base64Binary",
	"ms-exch-domainsecurity":                             "xsd:base64Binary",
	"ms-exch-labeleduri":                                 "xsd:base64Binary",
	"ms-fve-keypackage":                                  "xsd:base64Binary",
	"ms-fve-recoveryguid":                                "xsd:base64Binary",
	"ms-fve-recoverypassword":                            "xsd:base64Binary",
	"ms-fve-volumeguid":                                  "xsd:base64Binary",
	"ms-kds-dkhid":                                       "xsd:base64Binary",
	"ms-kds-domainid":                                    "xsd:base64Binary",
	"ms-kds-kdfparam":                                    "xsd:base64Binary",
	"ms-kds-privatekeyvalue":                             "xsd:base64Binary",
	"ms-kds-publickeyvalue":                              "xsd:base64Binary",
	"ms-kds-rootkeyguid":                                 "xsd:base64Binary",
	"ms-kds-secretagreementparam":                        "xsd:base64Binary",
	"ms-pki-accountcredentials":                          "xsd:base64Binary",
	"ms-pki-cacertificatehash":                           "xsd:base64Binary",
	"ms-pki-credential-roaming-tokens":                   "xsd:base64Binary",
	"ms-pki-dpcrl":                                       "xsd:base64Binary",
	"ms-pki-enrollmentservers":                           "xsd:base64Binary",
	"ms-pki-key-recovery-agent":                          "xsd:base64Binary",
	"ms-pki-oid-attribute":                               "xsd:base64Binary",
	"ms-pki-ra-application-policies":                     "xsd:base64Binary",
	"ms-pki-ra-policies":                                 "xsd:base64Binary",
	"ms-pki-roaming-time-stamp":                          "xsd:base64Binary",
	"ms-pki-site-name":                                   "xsd:base64Binary",
	"ms-pki-supersede-templates":                         "xsd:base64Binary",
	"ms-radius-savedkeys":                                "xsd:base64Binary",
	"ms-rras-attribute":                                  "xsd:base64Binary",
	"ms-sms-roamingboundaries":                           "xsd:base64Binary",
	"ms-wmi-classdefinition":                             "xsd:base64Binary",
	"ms-wmi-id":                                          "xsd:base64Binary",
	"ms-wmi-mof":                                         "xsd:base64Binary",
	"ms-wmi-query":                                       "xsd:base64Binary",
	"ms-wmi-scopeguid":                                   "xsd:base64Binary",
	"ms-wmi-sourceorganization":                          "xsd:base64Binary",
	"ms-wmi-stringdefault":                               "xsd:base64Binary",
	"ms-wmi-stringvalidvalues":                           "xsd:base64Binary",
	"ms-wmi-targetnamespace":                             "xsd:base64Binary",
	"ms-wmi-targetobject":                                "xsd:base64Binary",
	"mscomapartmentid":                                   "xsd:base64Binary",
	"mscomaplicationid":                                  "xsd:base64Binary",
	"mscomclsid":                                         "xsd:base64Binary",
	"mscominterfaceid":                                   "xsd:base64Binary",
	"mscomobjectid":                                      "xsd:base64Binary",
	"mscompartitionlink":                                 "xsd:base64Binary",
	"mscompartitionlinkbl":                               "xsd:base64Binary",
	"mscompartitionsetlink":                              "xsd:base64Binary",
	"mscompartitionsetlinkbl":                            "xsd:base64Binary",
	"mscomrolelink":                                      "xsd:base64Binary",
	"mscomrolelinkbl":                                    "xsd:base64Binary",
	"mscomtlbid":                                         "xsd:base64Binary",
	"mscomtypelibraryid":                                 "xsd:base64Binary",
	"mscomuserapplication":                               "xsd:base64Binary",
	"mscope-id":                                          "xsd:base64Binary",
	"msdfsr-computerreferencebl":                         "xsd:base64Binary",
	"msdfsr-conflictpath":                                "xsd:base64Binary",
	"msdfsr-defaultcompressionexclusion-filter":          "xsd:base64Binary",
	"msdfsr-deletedpath":                                 "xsd:base64Binary",
	"msdfsr-dfslinktarget":                               "xsd:base64Binary",
	"msdfsr-extensiondata":                               "xsd:base64Binary",
	"msdfsr-filefilter":                                  "xsd:base64Binary",
	"msdfsr-memberreference":                             "xsd:base64Binary",
	"msdfsr-memberreferencebl":                           "xsd:base64Binary",
	"msdfsr-ondemandexclusionfilefilter":                 "xsd:base64Binary",
	"msdfsr-replicationgroupguid":                        "xsd:base64Binary",
	"msdfsr-rootfenceid":                                 "xsd:base64Binary",
	"msdfsr-rootpath":                                    "xsd:base64Binary",
	"msdfsr-schedule":                                    "xsd:base64Binary",
	"msdfsr-stagingpath":                                 "xsd:base64Binary",
	"msdfsr-version":                                     "xsd:base64Binary",
	"msieee80211-data":                                   "xsd:base64Binary",
	"msieee80211-id":                                     "xsd:base64Binary",
	"msimaging-hashvalue":                                "xsd:base64Binary",
	"msimaging-pspidentifier":                            "xsd:base64Binary",
	"msimaging-thresholdhashvalue":                       "xsd:base64Binary",
	"msimaging-thumbprintshash":                          "xsd:base64Binary",
	"msipconfiguration":                                  "xsd:base64Binary",
	"msmq-digests":                                       "xsd:base64Binary",
	"msmq-digests-mig":                                   "xsd:base64Binary",
	"msmq-dstsite":                                       "xsd:base64Binary",
	"msmq-encrypt-key":                                   "xsd:base64Binary",
	"msmq-owner-id":                                      "xsd:base64Binary",
	"msmq-prev-site":                                     "xsd:base64Binary",
	"msmq-qm-id":                                         "xsd:base64Binary",
	"msmq-sign-key":                                      "xsd:base64Binary",
	"msmq-site-1":                                        "xsd:base64Binary",
	"msmq-site-2":                                        "xsd:base64Binary",
	"msmq-site-gates":                                    "xsd:base64Binary",
	"msmq-site-gates-mig":                                "xsd:base64Binary",
	"msmq-site-id":                                       "xsd:base64Binary",
	"msmq-sites":                                         "xsd:base64Binary",
	"msmq-user-account":                                  "xsd:base64Binary",
	"msnpcallinghours":                                   "xsd:base64Binary",
	"msnpsavedpassword":                                  "xsd:base64Binary",
	"mspcgroupcookiesid":                                 "xsd:base64Binary",
	"mspcgroupcookievalue":                               "xsd:base64Binary",
	"mspcupstreamcookievalue":                            "xsd:base64Binary",
	"msrras-admindictionary":                             "xsd:base64Binary",
	"msrras-attributeobjectid":                           "xsd:base64Binary",
	"msrras-serviceaddress":                              "xsd:base64Binary",
	"msrras-userdict":                                    "xsd:base64Binary",
	"msrras-vendor-attributeentry":                       "xsd:base64Binary",
	"msrras-vendor-id":                                   "xsd:base64Binary",
	"mssms-assignedsite":                                 "xsd:base64Binary",
	"mssms-boundaries":                                   "xsd:base64Binary",
	"mssms-defaultmp":                                    "xsd:base64Binary",
	"mssms-defaultmplist":                                "xsd:base64Binary",
	"mssms-devicesettingpackages":                        "xsd:base64Binary",
	"mssms-devicesupportedplatforms":                     "xsd:base64Binary",
	"mssms-mplist":                                       "xsd:base64Binary",
	"mssms-rangedipsubnet":                               "xsd:base64Binary",
	"mssms-rangeipsubnet":                                "xsd:base64Binary",
	"mssms-roamingboundaries":                            "xsd:base64Binary",
	"mssms-sitecode":                                     "xsd:base64Binary",
	"mstapolicyguid":                                     "xsd:base64Binary",
	"mstsalias":                                          "xsd:base64Binary",
	"mstsaliassecondary":                                 "xsd:base64Binary",
	"nonce":                                              "xsd:base64Binary",
	"ntsecuritydescriptor":                               "xsd:base64Binary",
	"omobjectclass":                                      "xsd:base64Binary",
	"objectguid":                                         "xsd:base64Binary",
	"objectsid":                                          "xsd:base64Binary",
	"otherloginworkstations":                             "xsd:base64Binary",
	"parentcaguid":                                       "xsd:base64Binary",
	"partialattributedeletionlist":                       "xsd:base64Binary",
	"partialattributeset":                                "xsd:base64Binary",
	"pendingcacertificates":                              "xsd:base64Binary",
	"pkienrollmentaccess":                                "xsd:base64Binary",
	"pkiextendedkeyusage":                                "xsd:base64Binary",
	"pkioverlapperiods":                                  "xsd:base64Binary",
	"pkiprivatekey":                                      "xsd:base64Binary",
	"pkisiteaffinity":                                    "xsd:base64Binary",
	"rdnattid":                                           "xsd:base64Binary",
	"replpropertymetadata":                               "xsd:base64Binary",
	"replicationschedule":                                "xsd:base64Binary",
	"repluptodatevector":                                 "xsd:base64Binary",
	"requiredcategories":                                 "xsd:base64Binary",
	"retiredrepldsncsignatures":                          "xsd:base64Binary",
	"roottrustanchor":                                    "xsd:base64Binary",
	"roveriderules":                                      "xsd:base64Binary",
	"sidhistory":                                         "xsd:base64Binary",
	"schemaclassguid":                                    "xsd:base64Binary",
	"schemaidguid":                                       "xsd:base64Binary",
	"securityidentifier":                                 "xsd:base64Binary",
	"segmentationrules":                                  "xsd:base64Binary",
	"serviceclassid":                                     "xsd:base64Binary",
	"serviceinstanceversion":                             "xsd:base64Binary",
	"supersededpolicies":                                 "xsd:base64Binary",
	"supplementalcredentials":                            "xsd:base64Binary",
	"syncmembershipfilter":                               "xsd:base64Binary",
	"trustauthincoming":                                  "xsd:base64Binary",
	"trustauthoutgoing":                                  "xsd:base64Binary",
	"unicodepwd":                                         "xsd:base64Binary",
	"universalgroups":                                    "xsd:base64Binary",
	"usercertificate":                                    "xsd:base64Binary",
	"userparameters":                                     "xsd:base64Binary",
	"userpassword":                                       "xsd:base64Binary",
	"userpkcs12":                                         "xsd:base64Binary",
	"voltableguid":                                       "xsd:base64Binary",
	"voltableidxguid":                                    "xsd:base64Binary",
	"winsockaddresses":                                   "xsd:base64Binary",
	"x500uniqueidentifier":                               "xsd:base64Binary",
}

// AttrXSIType returns the xsi:type that ADWS expects for the named AD attribute.
// The lookup is case-insensitive. Returns "xsd:string" for unknown attributes.
func AttrXSIType(attrName string) string {
	if t, ok := attrXSIType[strings.ToLower(attrName)]; ok {
		return t
	}
	return "xsd:string"
}

// EncodeAttrValue returns the (xsiType, encodedValue) pair ready for use in an
// ADWS SOAP request for the given attribute name and raw Go string value.
//
// For xsd:base64Binary attributes the raw bytes are base64-encoded (standard
// encoding with padding). For all other types the value is returned as-is:
// AD accepts Boolean, Integer, and LargeInteger values as their decimal string
// representation over ADWS (xsi:type="xsd:string" per MS-ADDM §2.3.4).
func EncodeAttrValue(attrName, rawValue string) (xsiType, encodedValue string) {
	xsiType = AttrXSIType(attrName)
	if xsiType == "xsd:base64Binary" {
		encodedValue = base64.StdEncoding.EncodeToString([]byte(rawValue))
	} else {
		encodedValue = rawValue
	}
	return xsiType, encodedValue
}
